#!/bin/bash

echo "applying patch"

CWD=./src/patch
echo cp "${CWD}/pdfkit.standalone.js.patch" ./node_modules/pdfkit/js/pdfkit.standalone.js
cp "${CWD}/pdfkit.standalone.js.patch" ./node_modules/pdfkit/js/pdfkit.standalone.js
